server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: registry-center

#服务注册中心实例的主机名
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/